
name: GitHub Actions Demo
on: [ push ]
jobs:
  Test:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo "The job was automatically triggered by s{{github.event_name}}event."
      - run: python main.py